version: "3.7"

services:
  yoru:
    build: .
    container_name: yoru.me
    image: yoru.me
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always